
INSERT INTO users(first_name, last_name, email, gender, date_of_birth, "password", status) VALUES('Myrvyn', 'Champkin', 'mchampkin1@people.com.cn', 'Polygender', '1969/12/12', '$2a$10$86VDM97EKiVKeqY1bHlgJ.sU8.Ovbb2krtGvd0.pw9m8Jr6Gx3XPm', 1); //F4cmpGuXe5
INSERT INTO users(first_name, last_name, email, gender, date_of_birth, "password", status) VALUES('Marcy', 'Paley', 'mpaley2@washington.edu', 'Agender', '1981/12/24', '$2a$10$7dYxBMbtGSmXCljMw.30QOjfLMzwTGT0Qt0mX4yK6lFppRdNC9Koa', 1); // sshktkCh
INSERT INTO users(first_name, last_name, email, gender, date_of_birth, "password", status) VALUES('Graeme', 'Avramovsky', 'gavramovsky3@miitbeian.gov.cn', 'Genderfluid', '1976/10/13', '$2a$10$qawYRmzC3OyjHDLA246KIubS/0kUySrxmNJ1GU0tsuVYXhq30B2w6', 1);// aTb9TNZte
INSERT INTO users(first_name, last_name, email, gender, date_of_birth, "password", status) VALUES('Zane', 'Trood', 'ztrood4@meetup.com', 'Non-binary', '2003/12/10', '$2a$10$XeizCXhf2SSZuirIq5kG.OB3n6D23wMdqXuJIsR4/Pv24cyARRLbm', 1); // 1Y9dBxpyqpi
INSERT INTO users(first_name, last_name, email, gender, date_of_birth, "password", status) VALUES('Ruby', 'Holdron', 'rholdron5@gnu.org', 'Male', '1989/07/30', '$2a$10$su8721e0HUgp8WNzluAOl.DMTCbYM/g2wA8sGpVTpwDKgACYRBlAm', 1); // rBvbl6M9gK
INSERT INTO users(first_name, last_name, email, gender, date_of_birth, "password", status) VALUES('Leo', 'Tuddall', 'ltuddall6@shutterfly.com', 'Bigender', '2002/10/12', '$2a$10$gy6lGkz94lhMKXmZABQDcOrgJpblLcfo2bvZDRC.gozdVg.vw5TuK', 1); // lBWljv
INSERT INTO users(first_name, last_name, email, gender, date_of_birth, "password", status) VALUES('Andras', 'Currin', 'acurrin7@wp.com', 'Genderfluid', '1977/10/28', '$2a$10$pRFnTxw8VsDr1V/iqZn59uisHqmGIGGdva5vcVbFJb56T/gHCqaxq', 1); // iaR6aTBTyco4
INSERT INTO users(first_name, last_name, email, gender, date_of_birth, "password", status) VALUES('Murial', 'Cornewell', 'mcornewell8@blog.com', 'Female', '1984/02/16', '$2a$10$1pBZQlB/2fuX5rhZjnsMqeZJK8ND3WRvsFIF/RxpPXbXe9smYs4xq', 1); // nt5zgKjsoVn
INSERT INTO users(first_name, last_name, email, gender, date_of_birth, "password", status) VALUES('Darla', 'Kelf', 'dkelf9@github.io', 'Genderqueer', '2004/10/28', '$2a$10$S.ypDvy2wOO6MSmw7PIiyO7wqD8H3Jre1clsdeSDszA36kqmDP7b2', 1); // FRwR5TxW
INSERT INTO users(first_name, last_name, email, gender, date_of_birth, "password", status) VALUES('Carissa', 'Busek', 'cbuseka@ed.gov', 'Female', '1973/08/15', '$2a$10$YJQJneMVPNiW3Crf6E0L4ep/cBM1EdQPlot66yxfRCbG0mYl/MbOm', 1); // otqImF
INSERT INTO users(first_name, last_name, email, gender, date_of_birth, "password", status) VALUES('Julee', 'Skewis', 'jskewisb@go.com', 'Agender', '1961/09/09', '$2a$10$h4.jtx0PJln6AilUZ2tMguc/.Fu.pQ32./Ku3UJ4hQ7Ot/vuDJHee', 1); // 1w3oU8xU